In [7]:
import numpy as np


In [8]:
#1. Create a null vector of size 10 but the fifth value which is 1.
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [9]:
#2. Create a vector with values ranging from 10 to 49.

a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
#3. Create a 3x3 matrix with values ranging from 0 to 8

b = np.arange(0,9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]

l = [1,2,0,0,4,0]
c = np.nonzero(l)
c

(array([0, 1, 4], dtype=int64),)

In [12]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.

l1 = np.random.random((10,10))
print(l1)
arr_min = l1.min()
arr_max = l1.max()
print('Minimum',arr_min)
print('Maximum',arr_max)

[[0.5663112  0.23442145 0.1382253  0.60180235 0.44426726 0.75451276
  0.39268915 0.03508469 0.96849859 0.54975503]
 [0.2833356  0.05069984 0.83721284 0.80631621 0.34765211 0.69319835
  0.32825719 0.57632105 0.71894673 0.62488234]
 [0.02108083 0.41166793 0.84902964 0.19614241 0.14376975 0.40524844
  0.04996885 0.80059931 0.93518639 0.16478978]
 [0.70209972 0.21819919 0.77292365 0.93084804 0.7181474  0.01176586
  0.31660313 0.00621354 0.74718763 0.18405889]
 [0.1994797  0.22926688 0.37566842 0.1499903  0.86105981 0.26887662
  0.58854638 0.44234996 0.7348309  0.47121072]
 [0.39677095 0.85884303 0.41789989 0.69428321 0.33047462 0.72544554
  0.97938    0.619056   0.66715833 0.74764166]
 [0.51402926 0.86712746 0.588079   0.92853748 0.42748872 0.12055151
  0.64412368 0.0710726  0.21004413 0.03164041]
 [0.139971   0.62106976 0.31308904 0.18694604 0.14259102 0.4930397
  0.55298079 0.47778494 0.0588119  0.55836812]
 [0.70359471 0.72009045 0.36655583 0.83779508 0.28029062 0.90239253
  0.66988811 

In [15]:
#6. Create a random vector of size 30 and find the mean value.
v = np.random.random(30)
v.mean()

0.5675511526914035