In [18]:
import numpy as np


In [6]:
#1. Create a null vector of size 10 but the fifth value which is 1.
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [5]:
#2. Create a vector with values ranging from 10 to 49.

a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
#3. Create a 3x3 matrix with values ranging from 0 to 8

b = np.arange(0,9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]

l = [1,2,0,0,4,0]
c = np.nonzero(l)
c

(array([0, 1, 4], dtype=int64),)

In [24]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.

l1 = np.random.random((10,10))
print(l1)
arr_min = l1.min()
arr_max = l1.max()
print('Minimum',arr_min)
print('Maximum',arr_max)

[[0.9357629  0.32546402 0.40722189 0.15163139 0.66689569 0.03443403
  0.708725   0.07773824 0.97689485 0.75252059]
 [0.76722056 0.4950576  0.17267833 0.09682312 0.73313302 0.50130155
  0.87961457 0.0221145  0.88291459 0.77340669]
 [0.38795043 0.0580059  0.54418159 0.60728651 0.73699776 0.22281373
  0.24745672 0.547328   0.98333894 0.63169294]
 [0.24629269 0.35230065 0.9680643  0.16961398 0.50365138 0.65262853
  0.73534197 0.98931202 0.82132985 0.55637726]
 [0.47187203 0.70171577 0.74687427 0.95821816 0.6011028  0.32775754
  0.94974235 0.44017518 0.05077964 0.71466655]
 [0.80809764 0.83395168 0.74323406 0.99949022 0.56174321 0.92434719
  0.15251115 0.19530627 0.67192053 0.57171001]
 [0.79095347 0.57077701 0.94407839 0.11485084 0.33213175 0.3427421
  0.99201381 0.78388016 0.68843575 0.37086261]
 [0.17951071 0.79882193 0.60980444 0.98876572 0.15389673 0.47929527
  0.85007609 0.50990424 0.77294755 0.67471394]
 [0.14217174 0.30617752 0.45332301 0.45945609 0.44508387 0.69559573
  0.25731103 

In [26]:
#6. Create a random vector of size 30 and find the mean value.

v = np.arange(0,31)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])